# Generated by Django 2.2.dev20180621213648 on 2018-11-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaNac', models.CharField(max_length=10)),
                ('telefono', models.BigIntegerField()),
                ('nombreUsuario', models.CharField(max_length=40, unique=True)),
                ('contraseñaUsuario', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=60)),
                ('comuna', models.CharField(max_length=60)),
                ('vivienda', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('raza', models.CharField(max_length=40)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
