# Generated by Django 2.1.3 on 2018-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('raza', models.CharField(max_length=40)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
