# Generated by Django 2.1.3 on 2018-11-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris3', '0002_auto_20181128_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatado',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
    ]
